# 1. AirFlow 3.1.5
# Пример из документации: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html
x-airflow-common:
  &airflow-common
  build:
    context: ${AIRFLOW_DEPLOY_CONF_PATH}
  env_file:
    - ${ENV_FILE_PATH:-.env}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_MAIN_USER}:${POSTGRES_MAIN_PASSWORD}@postgres/${POSTGRES_DB_NAME}
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_MAIN_USER}:${POSTGRES_MAIN_PASSWORD}@postgres/${POSTGRES_DB_NAME}
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    SPARK_HOME: '/opt/spark'
    SPARK_JARS_DIR: '/opt/spark/jars'
  volumes:
    - ${AIRFLOW_PROJ_DIR}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR}/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  profiles: [core, airflow]

# 2. Spark
# Вдохновлялся данным решением: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker/tree/master
x-spark-common:
  &spark-common
  build:
    context: ${SPARK_DEPLOY_CONF_PATH}
  env_file:
    - ${ENV_FILE_PATH:-.env}
  environment:
    SPARK_MASTER_URL: "spark://spark-master:7077"
    SPARK_MASTER_WEBUI_PORT: "8080"
    SPARK_WORKER_WEBUI_PORT: "8091"
  extra_hosts:
    - "localhost:host-gateway"
  healthcheck:
    test: ["CMD", "pidof", "java"]
    interval: 60s
    timeout: 10s
    retries: 5
    start_period: 60s
  volumes:
    - ${SPARK_JOBS_DIR}:/opt/spark/jobs
  deploy:
    resources:
      limits:
        cpus: '1.00'
        memory: 1024M
  profiles: [core, spark, sparkcluster]

# 3. Apache Ozone (S3)
# Пример из официальной инструкции: https://ozone.apache.org/docs/edge/start/startfromdockerhub.html
x-ozone-common:
   &ozone-common
   image: apache/ozone:2.1.0
   environment:
      &ozone-common-env
      OZONE-SITE.XML_hdds.datanode.dir: "/data/hdds"
      OZONE-SITE.XML_ozone.metadata.dirs: "/data/metadata"
      OZONE-SITE.XML_ozone.om.address: "ozone-om"
      OZONE-SITE.XML_ozone.om.http-address: "ozone-om:9874"
      OZONE-SITE.XML_ozone.recon.address: "ozone-recon:9891"
      OZONE-SITE.XML_ozone.recon.db.dir: "/data/metadata/recon"
      OZONE-SITE.XML_ozone.replication: "1"
      OZONE-SITE.XML_ozone.scm.block.client.address: "ozone-scm"
      OZONE-SITE.XML_ozone.scm.client.address: "ozone-scm"
      OZONE-SITE.XML_ozone.scm.datanode.id.dir: "/data/metadata"
      OZONE-SITE.XML_ozone.scm.names: "ozone-scm"
      OZONE-SITE.XML_ozone.hdds.scm.safemode.min.datanode: "1"
      OZONE-SITE.XML_ozone.hdds.scm.safemode.threshold.pct: "0"
      OZONE-SITE.XML_ozone.hdds.scm.safemode.healthy.pipeline.pct: "0"
      OZONE-SITE.XML_ozone.hdds.scm.safemode.atleast.one.node.reported.pipeline.pct: "0"
      no_proxy: "ozone-om,ozone-recon,ozone-scm,ozone-s3g,localhost,127.0.0.1"
   profiles: [core, ozone, spark]

# 4. Hive-Metastore
# Пример из документации: https://hive.apache.org/docs/latest/admin/setting-up-hive-with-docker/
x-hive-metastore-common:
  &hive-metastore-common
  build:
    context: ${HIVE_METASTORE_DEPLOY_CONF_PATH}
  environment:
    &hive-metastore-common-env
    - HIVE_METASTORE_DB_TYPE=postgres
    - HIVE_METASTORE_DB_HOST=${HIVE_METASTORE_DB_HOST}
    - HIVE_METASTORE_DB_NAME=${HIVE_METASTORE_DB_NAME}
    - HIVE_METASTORE_DB_USER=${HIVE_METASTORE_DB_USER}
    - HIVE_METASTORE_DB_PASS=${HIVE_METASTORE_DB_PASSWORD}
    - HIVE_CUSTOM_CONF_DIR=${HIVE_METASTORE_CONF_DIR}
  depends_on:
    postgres:
      condition: service_healthy
    ozone-om:
      condition: service_healthy
  ports:
    - "9083:9083"
  volumes:
    - ${HIVE_METASTORE_CONF_DIR}:/opt/hive/conf
    - ${HIVE_METASTORE_WORK_DIR}:/opt/hive/data/warehouse
  healthcheck:
    test: ["CMD", "pidof", "java"]
    interval: 60s
    timeout: 5s
    retries: 10
    start_period: 30s
  profiles: [core, spark, hive]

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_MAIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MAIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DB_DIR:-./postgres-db-volume}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_MAIN_USER}", "-d", "${POSTGRES_DB_NAME}"]
      interval: 30s
      retries: 5
      start_period: 5s
    restart: always
    profiles: [core, spark, airflow, hive]

  redis:
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    profiles: [core, airflow]

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 600s
      timeout: 100s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 600s
      timeout: 100s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
          export AIRFLOW_UID=$$(id -u)
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        echo
        echo "Creating missing opt dirs if missing:"
        echo
        mkdir -v -p /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Airflow version:"
        /entrypoint airflow version
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Running airflow config list to create default config file if missing."
        echo
        /entrypoint airflow config list >/dev/null
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Change ownership of files in /opt/airflow to ${AIRFLOW_UID}:0"
        echo
        chown -R "${AIRFLOW_UID}:0" /opt/airflow/
        echo
        echo "Change ownership of files in shared volumes to ${AIRFLOW_UID}:0"
        echo
        chown -v -R "${AIRFLOW_UID}:0" /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}

    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow
    depends_on:
      <<: *airflow-common-depends-on

  ozone-datanode:
    <<: *ozone-common
    ports:
        - "9864:9864"
    command: ["ozone","datanode"]
    environment:
        <<: *ozone-common-env
    volumes:
      - ./docker-volumes/ozone/datanode:/data
  ozone-om:
    <<: *ozone-common
    ports:
        - 9874:9874
    environment:
        <<: *ozone-common-env
        CORE-SITE.XML_hadoop.proxyuser.hadoop.hosts: "*"
        CORE-SITE.XML_hadoop.proxyuser.hadoop.groups: "*"
        ENSURE_OM_INITIALIZED: /data/metadata/om/current/VERSION
        WAITFOR: ozone-scm:9876
    command: ["ozone","om"]
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9874/"]
        interval: 60s
        timeout: 10s
        retries: 5
        start_period: 30s
    volumes:
      - ./docker-volumes/ozone/ozone-manager:/data
  ozone-scm:
    <<: *ozone-common
    ports:
        - 9876:9876
    environment:
        <<: *ozone-common-env
        ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
    command: ["ozone","scm"]
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9876/"]
        interval: 60s
        timeout: 10s
        retries: 5
        start_period: 30s
    volumes:
      - ./docker-volumes/ozone/storage-container-manager:/data
  ozone-recon:
    <<: *ozone-common
    ports:
        - 9888:9888
    environment:
        <<: *ozone-common-env
    command: ["ozone","recon"]
  ozone-s3g:
    <<: *ozone-common
    ports:
        - 9878:9878
    environment:
        <<: *ozone-common-env
    command: ["ozone","s3g"]
  ozone-httpfs:
    <<: *ozone-common
    ports:
        - 14000:14000
    environment:
        <<: *ozone-common-env
        CORE-SITE.XML_fs.defaultFS: "ofs://om"
    command: [ "ozone","httpfs" ]

  jupyterlab:
    build:
      context: ${JUPYTER_DEPLOY_CONF_PATH}
    ports:
      - "8888:8888"
      - "4045:4045"
    volumes:
      - ${JUPYTER_WORK_DIR}:/opt/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - AIRFLOW_URL=http://localhost:8080
      - OZONE_ENDPOINT_URL=http://ozone-s3g:9878
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
    profiles: [core, spark, jupyter, sparkcluster]

  hive-metastore:
    <<: *hive-metastore-common

  spark-master:
    <<: *spark-common    
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      ozone-scm:
        condition: service_healthy
      hive-metastore:
        condition: service_healthy  
    command: /opt/spark/sbin/start-master.sh

  spark-worker:
    <<: *spark-common
    ports:
      - "8091:8091"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}      
      - SPARK_WORKER_PORT=7078
      - SPARK_WORKER_WEBUI_PORT=8091
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      spark-master:
        condition: service_healthy
    command: /opt/spark/sbin/start-worker.sh ${SPARK_MASTER_URL}
